E-COMMERCE/Models/Negozio.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_COMMERCE.Models
{
    public partial class Negozio
    {
        public int IdNegozio { get; set; }
        public string Prodotto { get; set; }
    }
}

E-COMMERCE/Controllers/NegozioController.cs
using E_COMMERCE.Models;
using Microsoft.AspNetCore.Mvc;

namespace E_COMMERCE.Controllers
{
    public class NegozioController : Controller
    {
        private readonly ECOMMERCEContext _context;

        public NegozioController(ECOMMERCEContext context)
        {
            _context = context;
        }

        #region ELENCO CLIENTE

        public IActionResult ElencoClienti()
        {
            return View(_context.Clientes.ToList());
        }

        #endregion

        #region NUOVOCLIENTE
        [HttpGet]
        public IActionResult NuovoCliente(int id)
        {
            var record = _context.Clientes.Find(id);
            if (record == null)
            {
                return NotFound();
            }
            return View(record);           
        }

        [HttpPost]
        public IActionResult NuovoCliente(int id, string nome, string cognome)
        {
            var record = _context.Clientes.Find(id);
            if (record == null)
            {
                return NotFound();
            }
            record.IdCliente = id;
            record.Nome = nome;
            record.Cognome = cognome;
            _context.Clientes.Update(record);
            _context.SaveChanges();
            return RedirectToAction("ElencoClienti");
        }
        #endregion

        #region MODIFICACLIENTE
        [HttpGet]
        public IActionResult ModificaCliente(int id)
        {
            var record = _context.Clientes.Find(id);
            if (record == null)
            {
                return NotFound();
            }
            return View(record);
        }

        [HttpPost]
        public IActionResult ModificaCliente(int id, string nome, string cognome)
        {
            var record = _context.Clientes.Find(id);
            if (record == null)
            {
                return NotFound();
            }
            record.IdCliente = id;
            record.Nome = nome;
            record.Cognome = cognome;
            _context.Clientes.Update(record);
            _context.SaveChanges();
            return RedirectToAction("ElencoClienti");
        }
        #endregion

        #region ELENCOPRODOTTI
        public IActionResult ElencoProdotti()
        {
            return View(_context.Prodottos.ToList());
        }

        #endregion

        #region NUOVOPRODOTTO
        [HttpGet]
        public IActionResult NuovoProdotto() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult NuovoProdotto(Prodotto nuovoRecord)
        {
            _context.Prodottos.Add(nuovoRecord);
            _context.SaveChanges();
            return RedirectToAction("ElencoProdotti");
        }


        #endregion

        #region MODIFICA PRODOTTO
        [HttpGet]
        public IActionResult ModificaProdotto(int id)
        {
            var record = _context.Prodottos.Find(id);
            if (record == null)
            {
                return NotFound();
            }
            return View(record);
        }

        [HttpPost]
        public IActionResult ModificaProdotto(int id, string nome, float prezzo)
        {
            var record = _context.Prodottos.Find(id);
            if (record == null)
            {
                return NotFound();
            }
            record.IdProdotto = id;
            record.Nome = nome;
            record.Prezzo = prezzo ;
            _context.Prodottos.Update(record);
            _context.SaveChanges();
            return RedirectToAction("ElencoClienti");
        }
        #endregion
    }
}

E-COMMERCE/Views/Negozio/Create.cshtml
@model E_COMMERCE.Models.Negozio

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Negozio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdNegozio" class="control-label"></label>
                <input asp-for="IdNegozio" class="form-control" />
                <span asp-validation-for="IdNegozio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prodotto" class="control-label"></label>
                <input asp-for="Prodotto" class="form-control" />
                <span asp-validation-for="Prodotto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-COMMERCE/Views/Negozio/Delete.cshtml
@model E_COMMERCE.Models.Negozio

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Negozio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prodotto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prodotto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdNegozio" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

E-COMMERCE/Views/Negozio/Details.cshtml
@model E_COMMERCE.Models.Negozio

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Negozio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prodotto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prodotto)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdNegozio">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

E-COMMERCE/Views/Negozio/Edit.cshtml
@model E_COMMERCE.Models.Negozio

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Negozio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdNegozio" />
            <div class="form-group">
                <label asp-for="Prodotto" class="control-label"></label>
                <input asp-for="Prodotto" class="form-control" />
                <span asp-validation-for="Prodotto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-COMMERCE/Views/Negozio/ElencoClienti.cshtml
@model IEnumerable<Cliente>

@{
    ViewData["Title"] = "ElencoClienti";
}

<h1> ELENCO CLIENTI</h1>
<hr />
<a asp-controller="Negozio" asp-action="NuovoCliente"> INSERISCI UN NUOVO CLIENTE </a>
<br />


<table class="table table-bordered">

    <tr>
        <th>ID CLIENTE: </th>
        <th>NOME: </th>
        <th>COGNOME: </th>
    </tr>

 @foreach(var item in Model)
    {
      <tr>
            <td>@item.IdCliente</td>
            <td>@item.Nome </td>
            <td>@item.Cognome </td>
           
            <td> <a  asp-action="ModificaCliente" asp-route-id="@item.IdCliente"> ModificaCliente </a></td>
        </tr>

    }

</table>

E-COMMERCE/Views/Negozio/ElencoProdotti.cshtml
@model IEnumerable<Prodotto>
@{
    ViewData["Title"] = "ElencoProdotti";
}

<h1>ElencoProdotti</h1>
<hr />

<a asp-controller="Negozio" asp-action="NuovoProdotto"> INSERISCI UN NUOVO PRODOTTO </a>
<br />
<a asp-controller="Negozio" asp-action="ModificaProdotto"> MODIFICA UN PRODOTTO </a>
<br />

<table class="table table-bordered">

    <tr>
        <th>ID PRODOTTO: </th>
        <th>NOME: </th>
        <th>PREZZO: </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.IdProdotto</td>
            <td>@item.Nome </td>
            <td>@item.Prezzo </td>
            <td> <a  asp-action="NuovoProdotto" asp-route-id="@item.IdProdotto"> NuovoCliente </a></td>
            <td> <a  asp-action="ModificaProdotto" asp-route-id="@item.IdProdotto"> ModificaCliente </a></td>
        </tr>

    }

</table>

E-COMMERCE/Views/Negozio/Index.cshtml
@model IEnumerable<E_COMMERCE.Models.Negozio>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Prodotto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Prodotto)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdNegozio">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdNegozio">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdNegozio">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

E-COMMERCE/Views/Negozio/ModificaCliente.cshtml
@model Cliente

@{
    ViewData["Title"] = "ModificaCliente";
}

<h1>Mdifica Cliente</h1>
<hr />

<form method="post">
    <div class="container">
        <div class="row">
            <div class="col">
                ID Cliente:
            </div>
            <div class="col">
                <input type="text" name="id" value="@Model.IdCliente" readonly required />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                Nome:
            </div>
            <div class="col">
                <input type="text" name="nome" value="@Model.Nome" />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                Cognome:
            </div>
            <div class="col">
                <input type="text" name="cognome" value="@Model.Cognome" />
            </div>
        </div>
    </div>
   
    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col">
                <input type="submit" value="Salva" />
            </div>
        </div>
    </div>
</form>

E-COMMERCE/Views/Negozio/ModificaProdotto.cshtml
@model Prodotto
@{
    ViewData["Title"] = "ModificaProdotto";
}

<h1>ModificaProdotto</h1>

<form method="post">
    <div class="container">
        <div class="row">
            <div class="col">
                ID Prodotto:
            </div>
            <div class="col">
                <input type="text" name="id" value="@Model.IdProdotto" readonly required />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                Nome:
            </div>
            <div class="col">
                <input type="text" name="nome" value="@Model.Nome" />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                Prezzo:
            </div>
            <div class="col">
                <input type="text" name="cognome" value="@Model.Prezzo" />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col">
                <input type="submit" value="Salva" />
            </div>
        </div>
    </div>
</form>

E-COMMERCE/Views/Negozio/NuovoCliente.cshtml
@model Cliente
@{
    ViewData["Title"] = "NuovoCliente";
}

<h1>Inserisci un Nuovo Cliente</h1>

<form method="post">
    <div class="container">
        <div class="row">
            <div class="col">
                ID Cliente:
            </div>
            <div class="col">
                <input type="text" name="id" value=@Model.IdCliente />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                Nome:
            </div>
            <div class="col">
                <input type="text" name="nome" value=@Model.Nome />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                Cognome:
            </div>
            <div class="col">
                <input type="text" name="cognome" value=@Model.Cognome />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
            </div>

            <div class="col">
                <input type="submit" value="salva" />
            </div>
        </div>
    </div>
</form>

E-COMMERCE/Views/Negozio/NuovoProdotto.cshtml
@model Prodotto
@{
    ViewData["Title"] = "NuovoProdotto";
}

<h1>Inserisci un nuovo Prodotto</h1>
<hr />

<form method="post">
    <div class="container">
        <div class="row">
            <div class="col">
                ID Prodotto:
            </div>
            <div class="col">
                <input type="text" name="id" value=@Model.IdProdotto />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                Nome:
            </div>
            <div class="col">
                <input type="text" name="nome" value=@Model.Nome />
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                Prezzo:
            </div>
            <div class="col">
                <input type="text" name="cognome" value=@Model.Prezzo />
            </div>
        </div>
    </div>
   
    <div class="container">
        <div class="row">
            <div class="col">
            </div>

            <div class="col">
                <input type="submit" value="salva" />
            </div>
        </div>
    </div>
</form>